//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPastelaria.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoPastelaria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        internal static string ButtonLoginEntrar {
            get {
                return ResourceManager.GetString("ButtonLoginEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Cliente.
        /// </summary>
        internal static string ButtonMenuCadClient {
            get {
                return ResourceManager.GetString("ButtonMenuCadClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Funcionario.
        /// </summary>
        internal static string ButtonMenuCadFun {
            get {
                return ResourceManager.GetString("ButtonMenuCadFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar Produto.
        /// </summary>
        internal static string ButtonMenuCadProd {
            get {
                return ResourceManager.GetString("ButtonMenuCadProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuração.
        /// </summary>
        internal static string ButtonMenuConfig {
            get {
                return ResourceManager.GetString("ButtonMenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string ButtonMenuSobre {
            get {
                return ResourceManager.GetString("ButtonMenuSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string ButtonSobreVoltar {
            get {
                return ResourceManager.GetString("ButtonSobreVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ADM.
        /// </summary>
        internal static string CheckBoxAdm {
            get {
                return ResourceManager.GetString("CheckBoxAdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balcão.
        /// </summary>
        internal static string CheckBoxBalcao {
            get {
                return ResourceManager.GetString("CheckBoxBalcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF:.
        /// </summary>
        internal static string LabelCadCliCPF {
            get {
                return ResourceManager.GetString("LabelCadCliCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dias:.
        /// </summary>
        internal static string LabelCadCliDias {
            get {
                return ResourceManager.GetString("LabelCadCliDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Marca Fiado:.
        /// </summary>
        internal static string LabelCadCliFiado {
            get {
                return ResourceManager.GetString("LabelCadCliFiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome:.
        /// </summary>
        internal static string LabelCadCliNome {
            get {
                return ResourceManager.GetString("LabelCadCliNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-Senha:.
        /// </summary>
        internal static string LabelCadCliRSenha {
            get {
                return ResourceManager.GetString("LabelCadCliRSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha:.
        /// </summary>
        internal static string LabelCadCliSenha {
            get {
                return ResourceManager.GetString("LabelCadCliSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone:.
        /// </summary>
        internal static string LabelCadCliTelefone {
            get {
                return ResourceManager.GetString("LabelCadCliTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string LabelCadFunCPF {
            get {
                return ResourceManager.GetString("LabelCadFunCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        internal static string LabelCadFunID {
            get {
                return ResourceManager.GetString("LabelCadFunID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula.
        /// </summary>
        internal static string LabelCadFunMatricula {
            get {
                return ResourceManager.GetString("LabelCadFunMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string LabelCadFunNome {
            get {
                return ResourceManager.GetString("LabelCadFunNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ReSenha.
        /// </summary>
        internal static string LabelCadFunRSenha {
            get {
                return ResourceManager.GetString("LabelCadFunRSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string LabelCadFunSenha {
            get {
                return ResourceManager.GetString("LabelCadFunSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string LabelCadFunTelefone {
            get {
                return ResourceManager.GetString("LabelCadFunTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição produto.
        /// </summary>
        internal static string LabelCadProdDesc {
            get {
                return ResourceManager.GetString("LabelCadProdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome produto.
        /// </summary>
        internal static string LabelCadProdNome {
            get {
                return ResourceManager.GetString("LabelCadProdNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string LabelCadProdValor {
            get {
                return ResourceManager.GetString("LabelCadProdValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentual juros diario.
        /// </summary>
        internal static string LabelConfigJuros {
            get {
                return ResourceManager.GetString("LabelConfigJuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linguagem:.
        /// </summary>
        internal static string LabelConfigLinguagem {
            get {
                return ResourceManager.GetString("LabelConfigLinguagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Multa por atraso (RS).
        /// </summary>
        internal static string LabelConfigMulta {
            get {
                return ResourceManager.GetString("LabelConfigMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string LabelLoginSenha {
            get {
                return ResourceManager.GetString("LabelLoginSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario:.
        /// </summary>
        internal static string LabelLoginUser {
            get {
                return ResourceManager.GetString("LabelLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pasteleixons.
        /// </summary>
        internal static string LabelSobreNome {
            get {
                return ResourceManager.GetString("LabelSobreNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a loren loren loren loren.
        /// </summary>
        internal static string LabelSobreTexto {
            get {
                return ResourceManager.GetString("LabelSobreTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Linkseixons.
        /// </summary>
        internal static string LinkLabelSobreLink {
            get {
                return ResourceManager.GetString("LinkLabelSobreLink", resourceCulture);
            }
        }
    }
}
